name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Vercel
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install

      - name: Build the project
        run: yarn build

      - name: Run linter
        run: yarn lint

      # INFO Run tests requires a testing framework to be setup to run with guthub actions
      #- name: Run tests
      #  run: yarn test
